server:
  port: 5000

spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

array-persistence-client:
  service-name: array-persistence-service
  url: http://localhost:5000/array-persistence-service